gpi-install:
	cd backend-api; npm i
	cd frontend-site; npm i

gpi-run-mysql:
	cd lamp-mysql; docker-compose up

gpi-run-backend:
	cd backend-api; npm run start

gpi-run-frontend:
	cd frontend-site; npm run start
